### ISSUE TITLE
Content "pushed down" by TOC

### ISSUE THREAD

**Issue by fthommen** [LarsGit223/dokuwiki_note#12]
Hi,

_Re title: sorry, I don't know how to describe the problem better.  Please feel free to change the title if required._

I was referred to here from https://github.com/splitbrain/dokuwiki/issues/2751.

**Issue:**

Notes are "pushed down" when they are "too near" the TOC. See this screenshot:

![dockuwiki_toc_pushdown_2](https://user-images.githubusercontent.com/279232/56148225-1bfaa180-5faa-11e9-8b83-b77cc53ce73a.png)

Can this be changed in the `note` stylesheet in a way, that the TOC floats over the effective content instead of pushing it away?

f.

**Comment by lpaulsen93** [comment]
Please try to manually install the note plugin from this URL: https://github.com/LarsGit223/dokuwiki_note/archive/toc.zip. The change does not let the TOC float over the note but it moves the note to the left and it's not pushed down anymore.

Please test and let me know what you think about the solution.

**Comment by fthommen** [comment]
Great solution. This is an even better behaviour than the one suggested by me.  Thanks a lot.
