### ISSUE TITLE
thumbnails not displayed in the actions bar

### ISSUE THREAD

**Issue by trebmuh** [LarsGit223/dokuwiki_note#15]
Hi @LarsGit223 .

I've installed this plugin on a 2018-04-22b "Greebo" dokuwiki and when editing a page, the icons aren't displayed in the actions bar. See :

![bogue-noteplugin-dokuwiki](https://user-images.githubusercontent.com/8705846/65350465-156df700-dbe6-11e9-86e7-7e92559b4c32.png)

The dark-grey rectangle is displayed when I click on the single white kind-of-dash on the right of the red-A icon.

I can get the code tags to display with clicking on the 4 little white kind-of-dash (in the dark-grey rectangle in the picture above).

**Comment by markalex2209** [comment]
Hello.
In my case it happened because my basedir is different from '/'.
Problem is in absolute path placed in action.php. 
As local solution I placed '../..' instead of '/lib' in beginning of all icon paths in action.php

**Comment by gerardnico** [comment]
I came to this issue because I got a lot of errors in the web server log. 

Cheers
Nico

**Comment by lpaulsen93** [comment]
@gerardnico I merged your patch, thanks.

@trebmuh, @markalex2209, @gerardnico Please re-install current master (there will be no update message yet) and test.

**Comment by gerardnico** [comment]
@LarsGit223 Thanks! It's working for me.

**Comment by lpaulsen93** [comment]
The change is now officially released, closing this now.
