### ISSUE TITLE
Font color issue in lists

### ISSUE THREAD

**Issue by asheenlevrai** [LarsGit223/dokuwiki_note#16]
Hi,

In notes, the text is displayed in black by default (over the color background corresponding to each type of notes).
However, when creating lists in notes, the font color for the listed entries changes to the color defined as "Main text color" in DW Template Style Settings.

This is problematic when this settings is white, for instance for dark themes wikis, since it makes the text (for lists placed into notes) unreadable when the background color is too similar to the text color.

A good solution would be to make sure that the text in notes is ALWAYS black, even for lists (since the background of notes is probably never going to be set to black.

Thanks
-a-

**Comment by lpaulsen93** [comment]
The solution is not beautiful because I used the CSS keyword `!important`, but it should be fixed now. Please re-install and test.

**Comment by asheenlevrai** [comment]
Thanks a lot,

I tested before and after re-installing the plugin and indeed the lists now appear in black text.

Tx again
-a-

**Comment by lpaulsen93** [comment]
The change is now officially released, closing this now.
