### ISSUE TITLE
does not work in rc2020-06-01 "Hogfather"

### ISSUE THREAD

**Issue by hartl** [LarsGit223/dokuwiki_note#17]
not working in rc2020-06-01 "Hogfather" if a link is in the note.

**Comment by lpaulsen93** [comment]
Thanks for reporting the issue. I will try to work on this on the upcoming weekend.

**Comment by lpaulsen93** [comment]
Please update to DokuWiki release `rc2-2020-06-01 "Hogfather" RC2`. It seems to work fine for me with that version.

**Comment by lpaulsen93** [comment]
A little addition:
There is still an issue if a page uses the `~~NOCACHE~~` feature. But at the moment I assume it is a problem in the DokuWiki core and not in this plugin. It seems to be related to this DokuWiki issue: https://github.com/splitbrain/dokuwiki/issues/3129.

**Comment by mgiugliano** [comment]
I am experiencing similar problems, as soon as I upgraded to rc2-2020-06-01 "Hogfather" RC2 (PHP version 7.1.11), with or without links in the note content.

I note that, when activating "preview", the "warnings", "hints", etc. are correctly rendered. Afterwards, upon saving the page and reloading, they are no longer visible, leaving the text they contain completely hidden.

**Comment by lpaulsen93** [comment]
As assumed earlier this really seems to be a problem in DokuWiki "Hogfather" RC2. It seems to work fine with the latest development version so we have to wait for the next release/release candidate to get this fixed officially.

**Comment by ZagSar** [comment]
For the Dokuwiki I manage, the notes were not showing up on half of the pages. There was no pattern, it was seemingly random. I was able to fix it by simply disabling and re-enabling the plugin.

Hopefully somebody finds this helpful down the road.

**Comment by lpaulsen93** [comment]
The plugin seems to work fine for me with Release **_rc-2020-06-09 "Hogfather" RC3_**. So I close this now. If anyone still got problems, then please re-open the issue.
