### ISSUE TITLE
Notes not appearing on some pages

### ISSUE THREAD

**Issue by maxparkinsondev** [LarsGit223/dokuwiki_note#18]
After the update to Hogfather RC2, some notes work as expected, but on some pages they do not appear at all. I have not been able to find a pattern. When looking in the error log, I found these error messages:

    PHP message: PHP Warning:  Use of undefined constant DOKU_LEXER_UNMATCHED - assumed 'DOKU_LEXER_UNMATCHED' (this will throw an Error in a future version of PHP) in /var/www/dokuwiki/lib/plugins/note/syntax.php on line 110
    PHP message: PHP Warning:  Use of undefined constant DOKU_LEXER_EXIT - assumed 'DOKU_LEXER_EXIT' (this will throw an Error in a future version of PHP) in /var/www/dokuwiki/lib/plugins/note/syntax.php on line 114
    PHP message: PHP Warning:  Use of undefined constant DOKU_LEXER_ENTER - assumed 'DOKU_LEXER_ENTER' (this will throw an Error in a future version of PHP) in /var/www/dokuwiki/lib/plugins/note/syntax.php on line 106

The server is using PHP 7.2, would that be a problem?

Thanks

**Comment by lpaulsen93** [comment]
Hogfather RC1 and RC2 have issues which affect the notes plugin, also see #17. Hogfather RC3 should owrk fine but I did not test it yet.

**Comment by maxparkinsondev** [comment]
Thanks, I was not reading #17 closely enough, I didn't even realize that RC3 had been released yet. My bad.

**Comment by lpaulsen93** [comment]
Never mind.
