### ISSUE TITLE
Notes are unreadable on dark theme setups

### ISSUE THREAD

**Issue by MarcinOrlowski** [LarsGit223/dokuwiki_note#2]
Notes are unreadable on dark theme setups due to missing `color` set in CSS which in case of dark theme is usually white (or light) and all the texts blends in light notes backgrounds.

I created PR #1 that fixes that.

**Comment by lpaulsen93** [comment]
Could you let me know which template you are uisng (to do my own tests). Thanks.

**Comment by MarcinOrlowski** [comment]
I am using bootstrap3 and my theme is `Darkly`.

**Comment by lpaulsen93** [comment]
Please re-test with current master.

**Comment by lpaulsen93** [comment]
Did you have a chance to test this with the current master version?

**Comment by lpaulsen93** [comment]
I just created a new release with your changes included. So this can be closed.

**Comment by MarcinOrlowski** [comment]
But this is broken. Notes are unreadable after your release.

**Comment by lpaulsen93** [comment]
Sorry, the download URL on the plugin page still pointed to the old release. Please update again.

**Comment by MarcinOrlowski** [comment]
Better now :)
